=== asen-krasimirov/xml-uni-project/museums.dtd
<!ELEMENT catalogue (regions, museum-types, museums)>
<!ELEMENT regions (region+)>
<!ELEMENT region (name)>
<!ATTLIST region regionId ID #REQUIRED>

<!ELEMENT museum-types (type+)>
<!ELEMENT type (name)>
<!ATTLIST type typeId ID #REQUIRED>

<!ELEMENT museums (museum+)>
<!ELEMENT museum (name, description, images, additionalInfo)>
<!ATTLIST museum museumId ID #REQUIRED>
<!ATTLIST museum regionRef IDREF #REQUIRED>
<!ATTLIST museum typeRef IDREF #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT images (image+)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT additionalInfo (phone, workingHours, address)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT workingHours (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ENTITY nhm_image1 "images/nhm1.jpg">
<!ENTITY nhm_image2 "images/nhm2.jpg">

<!ENTITY nag_image1 "images/nag1.jpg">
<!ENTITY nag_image2 "images/nag2.jpg">

<!ENTITY am_image1 "images/am1.jpg">
<!ENTITY am_image2 "images/am2.jpg">

<!ENTITY em_image1 "images/em1.jpg">
<!ENTITY em_image2 "images/em2.jpg">

<!ENTITY vnm_image1 "images/vnm1.jpg">
<!ENTITY vnm_image2 "images/vnm2.jpg">

<!ENTITY rhm_image1 "images/rhm1.jpg">
<!ENTITY rhm_image2 "images/rhm2.jpg">

<!ENTITY soc_image1 "images/soc1.jpg">
<!ENTITY soc_image2 "images/soc2.jpg">

<!ENTITY pmb_image1 "images/pmb1.jpg">
<!ENTITY pmb_image2 "images/pmb2.jpg">

=== asen-krasimirov/xml-uni-project/museums.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "museums.dtd">
<?xml-stylesheet type="text/xsl" href="museums.xsl"?>

<catalogue>
    <regions>
        <region regionId="SOF">
            <name>София</name>
        </region>
        <region regionId="PLD">
            <name>Пловдив</name>
        </region>
        <region regionId="VAR">
            <name>Варна</name>
        </region>
        <region regionId="BURG">
            <name>Бургас</name>
        </region>
    </regions>

    <museum-types>
        <type typeId="NAT">
            <name>Национален</name>
        </type>
        <type typeId="ART">
            <name>Художествен</name>
        </type>
        <type typeId="ARC">
            <name>Археологически</name>
        </type>
        <type typeId="ETH">
            <name>Етнографски</name>
        </type>
    </museum-types>

    <museums>
        <museum museumId="NHM" regionRef="SOF" typeRef="NAT">
            <name>Национален исторически музей</name>
            <description>
            Националният исторически музей (НИМ) е най-големият музей в България, съхраняващ над 650 000 културни ценности. 
            Разположен в бившата резиденция на Тодор Живков, музеят представя богатата история на България от древността до наши дни. 
            Колекциите включват тракийски съкровища, средновековни реликви, възрожденски артефакти и предмети от модерната епоха. 
            Посетителите могат да разгледат интерактивни експозиции и специални временни изложби, които представят уникални находки.
            </description>
            <images>
                <image>&nhm_image1;</image>
                <image>&nhm_image2;</image>
            </images>
            <additionalInfo>
                <phone>02 955 4280</phone>
                <workingHours>10:00ч.–18:00ч.</workingHours>
                <address>ул. "Витошко лале" 16, София</address>
            </additionalInfo>
        </museum>
        
        <museum museumId="NAG" regionRef="SOF" typeRef="ART">
            <name>Национална художествена галерия</name>
            <description>
            Националната художествена галерия е водещият музей за българско и световно изобразително изкуство.
            Галерията разполага с над 50 000 произведения, включително картини, скулптури и графики от различни исторически периоди.
            Сред експонатите са творби на български класици като Владимир Димитров-Майстора и Златю Бояджиев.
Галерията редовно организира временни изложби, представящи съвременни и международни художници.
            </description>
            <images>
                <image>&nag_image1;</image>
                <image>&nag_image2;</image>
            </images>
            <additionalInfo>
                <phone>02 980 0073</phone>
                <workingHours>10:00ч.–18:00ч.</workingHours>
                <address>пл. "Княз Александър I" 1, София</address>
            </additionalInfo>
        </museum>

        <museum museumId="AM" regionRef="PLD" typeRef="ARC">
            <name>Археологически музей - Пловдив</name>
            <description>
            Археологическият музей в Пловдив съхранява богата колекция от артефакти, датиращи от неолита до късното средновековие. 
            Музеят предлага на посетителите ценни находки от тракийски, римски и византийски селища в региона. 
            Сред експонатите са златни маски, римски мозайки и монети от древни цивилизации. 
Специалните изложби и интерактивни експозиции представят развитието на човешката култура през хилядолетията. 
            </description>
            <images>
                <image>&am_image1;</image>
                <image>&am_image2;</image>
            </images>
            <additionalInfo>
                <phone>032 624 339</phone>
                <workingHours>09:00ч.–17:30ч.</workingHours>
                <address>ул. "Съборна" 1, Пловдив</address>
            </additionalInfo>
        </museum>

        <museum museumId="VNM" regionRef="VAR" typeRef="ARC">
            <name>Варненски археологически музей</name>
            <description>
            Варненският археологически музей съхранява едни от най-ценните находки в България, включително най-старото обработено злато в света – Варненското златно съкровище.
            Експозицията представя артефакти от неолита, тракийската, римската и византийската епоха.
            Сред експонатите са антични керамики, монети, накити и оръжия, открити в района на Варна и Черноморието.
            </description>
            <images>
                <image>images/vnm1.jpg</image>
                <image>images/vnm2.jpg</image>
            </images>
            <additionalInfo>
                <phone>052 612 207</phone>
                <workingHours>10:00ч.–18:00ч.</workingHours>
                <address>ул. "Съборна" 41, Варна</address>
            </additionalInfo>
        </museum>

        <museum museumId="RHM" regionRef="BURG" typeRef="ETH">
            <name>Регионален исторически музей - Бургас</name>
            <description>
            Музеят представя богатата история на Бургас и региона от древността до модерната епоха.
            Колекциите включват тракийски съкровища, римски артефакти, средновековни монети и предмети от българското възраждане.
            Интерес представляват и етнографските експозиции, разкриващи традиционния бит и култура на местното население.
            </description>
            <images>
                <image>&rm_image1;</image>
                <image>&rm_image2;</image>
            </images>
            <additionalInfo>
                <phone>056 842 170</phone>
                <workingHours>09:00ч.–17:30ч.</workingHours>
                <address>ул. "Лермонтов" 31, Бургас</address>
            </additionalInfo>
        </museum>

        <museum museumId="SOC" regionRef="SOF" typeRef="ETH">
            <name>Музей на социализма</name>
            <description>
            Музеят на социализма пресъздава живота в България през комунистическия период (1944 – 1989 г.).
            Експозицията включва пропагандни плакати, паметници, униформи, битови предмети и автомобили от епохата.
            Посетителите могат да разгледат възстановени социалистически жилища и да научат повече за идеологията и ежедневието през този период.
            </description>
            <images>
                <image>images/soc1.jpg</image>
                <image>images/soc2.jpg</image>
            </images>
            <additionalInfo>
                <phone>02 931 3119</phone>
                <workingHours>10:00ч.–18:00ч.</workingHours>
                <address>ул. "Цар Освободител" 2, София</address>
            </additionalInfo>
        </museum>

        <museum museumId="EM" regionRef="PLD" typeRef="ETH">
            <name>Етнографски музей - Пловдив</name>
            <description>
             Разположен в красива възрожденска къща, музеят представя традиционния бит, облекло и занаятчийство на населението от Пловдивския регион.
            Колекциите включват народни носии, накити, музикални инструменти и домакински предмети от 18-19 век.
            Специална част от изложбата е посветена на старите занаяти като грънчарство, тъкачество и дърворезба.
            </description>
            <images>
                <image>&em_image1;</image>
                <image>&em_image2;</image>
            </images>
            <additionalInfo>
                <phone>032 626 868</phone>
                <workingHours>09:00ч.–17:30ч.</workingHours>
                <address>ул. "Д-р Стоян Чомаков" 2, Пловдив</address>
            </additionalInfo>
        </museum>

        <museum museumId="PMB" regionRef="BURG" typeRef="NAT">
            <name>Природонаучен музей - Бургас</name>
            <description>
                Природонаучнният музей в Бургас е единствен в района на Югоизточното Черноморие.
                Експозицията представя геоисторическото развитие и съвременното природно разнообразие на Югоизточна България и съдейства за опазването на уникалната природа на региона.
                Разполага с уникалните колекции ”Магичният свят на камъка”, ”Флора и фауна на планината Странджа”, ”Птичи ресурси на бургаските влажни зони”.
            </description>
            <images>
                <!-- <image>&pmb_image1;</image> -->
                <!-- <image>&pmb_image2;</image> -->
                <image>images/pmb1.jpg</image>
                <image>images/pmb2.jpg</image>
            </images>
            <additionalInfo>
                <phone>056 844 901</phone>
                <workingHours>10:00ч.–18:00ч.</workingHours>
                <address>ул. "К. Фотинов" 30, Бургас</address>
            </additionalInfo>
        </museum>

    </museums>
</catalogue>
